/smart_radar:
  ros__parameters:
    master_inst_serial_type: "can_based"
    master_data_serial_type: "can_based"
    adapters:
      adapter_0:
        hw_type: "can"
        hw_dev_id: 2
        hw_iface_name: "can0"
        baudrate: 500000

    sensors:
      # As many as 10 sensors all named as "sensor_<number>" in increasing order of numbers,
      # e.g., sensor_0, sensor_1, etc. The list must start with sensor_0.
      # For sensor `model`if using :
      # can: 'umrra4_can_v1_0_1', 'umrr96_can', 'umrr11_can', 'umrr9d_can_v1_0_3', 'umrr9d_can_v1_2_2', 'umrr9f_can_v2_1_1', 'umrr9f_can_v2_2_1'
      # port: 'umrra4_v1_0_1', 'umrr96', 'umrr11', 'umrr9d_v1_0_3', 'umrr9d_v1_2_2', 'umrr9f_v1_1_1', 'umrr9f_v2_1_1', 'umrr9f_v2_2_1'
      sensor_0:
        link_type: "can"
        # The model of the connected sensor.
        model: "umrr9d_can_v1_5_0"
        # Adapter id to which sensor is connected
        dev_id: 2
        # The client_id of the sensor/source, must be a unique integer.
        id: 100
        # The port to be used.
        port: 55555
        # The frame_id to be set to the published messages.
        frame_id: "umrr"
        # Specify the history size.
        history_size: 10
        # The interface name of the sensor
        uifname: "umrr9d_t152_automotive"
        # The major version of the interface
        uifmajorv: 1
        # The minor version of the interface
        uifminorv: 5
        # The pathc version of the interface
        uifpatchv: 0
