#####################################################################################################
##
## Copyright (c)  2024, Microstrain by HBK
##
## Use of this source code is governed by an MIT-style
## license that can be found in the LICENSE file or at
## https://opensource.org/licenses/MIT.
##
#####################################################################################################

# Configuration Settings for C94-M8P device
ublox_gps_node:
  ros__parameters:
    debug: 0 # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyACM1
    frame_id: gps
    uart1:
      baudrate: 9600

    # TMODE3 Config
    tmode3: 0 # Survey-In Mode

    inf:
      all: true # Whether to display all INF messages in console

    publish:
      all: true
      aid:
        hui: false
      nav:
        posecef: false
