# Configuration Settings for C94-M8P device
ublox_gps_node:
  ros__parameters:
    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyACM1
    frame_id: gps
    uart1:
      baudrate: 9600
    
    gnss:
      glonass: false
      beidou: false
      gps: true
      qzss: false
      galileo: false
      imes: false
    
    # TMODE3 Config
    tmode3: 0                   # Survey-In Mode
    # sv_in:
    #   reset: True               # True: disables and re-enables survey-in (resets)
    #                             # False: Disables survey-in only if TMODE3 is
    #                             # disabled
    #   min_dur: 300              # Survey-In Minimum Duration [s]
    #   acc_lim: 3.0              # Survey-In Accuracy Limit [m]

    dynamic_model: automotive

    inf:
      all: true                   # Whether to display all INF messages in console
    
    publish:
      all: false
      aid:
        hui: false
      nav:
        all: true
        relposned: true
        posllh: true
        posecef: true
